source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
#inhibit_all_warnings!

def common
    pod 'WeexSDK'
end

target 'BaalDemo' do
    common
end

target 'BaalDemoTests' do
    common
end
