source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
#inhibit_all_warnings!

def common
    pod 'WeexSDK', :git =>'https://github.com/apache/incubator-weex.git', :tag => '0.17.0'
end

target 'BaalDemo' do
    common
end

target 'BaalDemoTests' do
    common
end
